# Generated by Django 3.0.3 on 2020-06-16 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chart', '0008_death'),
    ]

    operations = [
        migrations.CreateModel(
            name='Percapita',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateTimeField()),
                ('Korea_South', models.FloatField(null=True)),
                ('Germany', models.FloatField(null=True)),
                ('United_Kingdom', models.FloatField(null=True)),
                ('US', models.FloatField(null=True)),
                ('France', models.FloatField(null=True)),
                ('China', models.FloatField(null=True)),
            ],
        ),
    ]
